### ISSUE TITLE
TaskExecutionRole name is a mixture of snake case and kebab case

### ISSUE THREAD

**Issue by yutaka0m** [terraform-aws-modules/terraform-aws-atlantis#130]
Hi everyone.

https://github.com/terraform-aws-modules/terraform-aws-atlantis/blob/cc2ed041af0c6e1b30716e16de1084280726cf0b/main.tf#L369

I think it's better to unify this name with kebab case or snake case 🤔 

```
"${var.name}_ecs_task_execution"
or
"${var.name}-ecs-task-execution"
```

How does that sound??

**Comment by antonbabenko** [comment]
Hi @yutaka0m !

This sounds like a breaking change for me now, and I would prefer to not introduce any BC unless it is really necessary.

Closing this issue.
