### ISSUE TITLE
Use existing ALB

### ISSUE THREAD

**Issue by ivanmartos** [terraform-aws-modules/terraform-aws-atlantis#139]
Idea is to add an option of re-using existing ALB, not to create new atlantis-specific ALB

This would mean that some vars would need to be added and to change implementation a bit

Motivation - ALB just for atlantis can get expensive :)

**Comment by antonbabenko** [comment]
Hi @ivanmartos !

This issue makes sense but the complexity it introduces does not make it feasible in my opinion.

PS: ALB is not the same as ELB. ALB costs nothing if not used, but ELB costs money. Please check this for a detailed comparison of prices between ELB and ALB - https://aws.amazon.com/elasticloadbalancing/pricing/

Closing this issue.
