### ISSUE TITLE
Integrate Atlantis with terraform-aws-modules repositories

### ISSUE THREAD

**Issue by antonbabenko** [terraform-aws-modules/terraform-aws-atlantis#14]
To-do:
- [x] Run Atlantis service on AWS using [terraform-aws-atlantis](https://github.com/terraform-aws-modules/terraform-aws-atlantis)
- [ ] Once PR is created - run `atlantis plan` automatically
- [ ] Allow `atlantis apply` only for specific github accounts to execute `examples`
- [ ] Run `terraform destroy` for the executed examples once PR is merged to cleanup resources
- [ ] Make generic `atlantis.yaml` which suits all terraform-aws-modules

**Comment by chenrui333** [comment]
that seems pretty good idea, what would be the account to deploy this ECS cluster?

**Comment by antonbabenko** [comment]
I have opened a new AWS account just for this, and wrote approx 40% of the code required to run `atlantis plan`, because it is pretty much doable, but `atlantis apply` requires much more work to make it secure enough.
