### ISSUE TITLE
Using TaskRole and AssumeRole for crossaccount provisioning

### ISSUE THREAD

**Issue by bdelage** [terraform-aws-modules/terraform-aws-atlantis#145]
Hello there

I'm trying to use AWS roles to authorize Terraform/Atlantis to manage resources in another account.
I set it up like this : 

Atlantis runs in its own account (let's call it <atlantis_account>), with its own taskExecutionRole which is the same as the TaskRole with the default name `atlantis-ecs_task_execution`.
This role has an additional inline policy like :
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::<target_account>:role/AtlantisRole"
        }
    ]
}
```
So it can AssumeRole a role in the target account.

In the other account, I created the role with `AdministratorAccess` policy, and I set a trust relationship to the `atlantis-ecs_task_execution` role in the in the <atlantis_account>  : 
```
{
  "Version": "2008-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::<atlantis_account>:role/atlantis-ecs_task_execution"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

In my repository, I have a provider and terraform blocks like this : 
```
provider "aws" {
  assume_role {
    region        = "us-east-1"
    role_arn     = "arn:aws:iam::<target_account>:role/AtlantisRole"
  }
}
terraform {
  required_version = ">= 0.12"
  backend "s3" {
    bucket   = "mybucket"
    key         = "tf-atlantis-testing/terraform.state"
    region    = "us-east-1"
    role_arn  = "arn:aws:iam::<target_account>:role/AtlantisRole"
  }
}

```

When Atlantis run, I get : 
```
running "/usr/local/bin/terraform init -input=false -no-color -upgrade" in "/home/atlantis/.atlantis/repos/my_org/tf-atlantis-testing/1/default": exit status 1

Initializing the backend...

Error: The role "arn:aws:iam::<target_account>:role/AtlantisRole" cannot be assumed.

  There are a number of possible causes of this - the most common are:
    * The credentials used in order to assume the role are invalid
    * The credentials do not have appropriate permission to assume the role
    * The role ARN is not valid
```

I was under the impression Terraform will fetch the credentials from the env variable `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` and since the TaskRole has permission to assume the role in the target account, it should be able to.

Am I missing something ? 

**Update :** 
It seems the issue is only to access the backend. And it's due to the fact that Terraform does not use the same order to fetch credentials for the backend and the credentials to actually provision resource. 
It will be fixed in TF 0.13 :
Issue : https://github.com/hashicorp/terraform/issues/24253
Commit : https://github.com/hashicorp/terraform/commit/8f430b4b1e633ba6c1f549312a031c12dd525313

As a workaround I removed the role_arn to access the backend, and put a bucket-policy on the remote S3 bucket referencing my `atlantis-ecs_task_execution` role.

Here is what I get now :
```
running "/usr/local/bin/terraform init -input=false -no-color -upgrade" in "/home/atlantis/.atlantis/repos/my_org/tf-atlantis-testing/1/default": exit status 1

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Error refreshing state: AccessDenied: Access Denied
	status code: 403, request id: XXXXXXXXXXXXXXXX, host id: XXXXXXXXXXXXXXX
```

Which is a bit better, but I'm not there yet.

It very much looks like the following issue https://github.com/hashicorp/terraform/issues/18801
I'll keep investigating.

**Comment by bryantbiggs** [comment]
@bdelage you should remove the role arn from the backend configuration as the `"arn:aws:iam::<atlantis_account>:role/atlantis-ecs_task_execution"` role will be the one accessing the backend which you have created in the account where atlantis is running. 

```hcl
terraform {
  required_version = ">= 0.12"
  backend "s3" {
    bucket   = "mybucket"
    key         = "tf-atlantis-testing/terraform.state"
    region    = "us-east-1"
  }
}
```

**Comment by Marcvd316** [comment]
Hi @bryantbiggs,

I'm working with @bdelage on this.

In his comment above, he pasted the error we get _with_ and _without_ the _role_arn_ argument in the backend block.
Different errors, but still a no go either way.

**Comment by bryantbiggs** [comment]
can you do me a favor and check the state files in your terraform backend bucket - specifically around the object permissions and ensuring the bucket owner has read and write access on the files currently

**Comment by Marcvd316** [comment]
The bucket is empty, the state file has not even been created yet.
As for the bucket owner permissions, yes it has all permissions:
![image](https://user-images.githubusercontent.com/31293815/90416270-42d65580-e080-11ea-9c46-45e4f238c7fb.png)
We even tried explicitly specifying cross-account permissions using bucket policies, no go.

I get the impression this is an issue with cross-account role assumption of the Fargate container, because if we use store the state files in a bucket in the same account as the Fargate task, it works as expected.

Thanks for your help

**Comment by bryantbiggs** [comment]
@Marcvd316 my apologies, I mis-understood your setup. I thought your S3 bucket was in the same account as Atlantis. I typically have Atlantis and the state bucket stored in a "Shared Services" account and the ECS task role ask access to assume roles out to each of the sub-accounts to manage resources. 

This sounds like you have Atlantis in an account, and a state bucket in each of your sub-accounts. I will have to try looking a little deeper at that when I get some time, but it should be possible for sure.

**Comment by bdelage** [comment]
Hi guys
Thank you for following up on this issue.
I actually found a solution as I was back from vacation : 

```
terraform {
  required_version = ">= 0.13"
  backend "s3" {
    bucket   = "mybucket"
    key      = "tf-atlantis-testing/terraform.state"
    region   = "us-east-1"
    role_arn     = "arn:aws:iam::<target account>:role/AtlantisRole"
    session_name = "tf-atlantis-testing"
    dynamodb_table = "<terraform-remote-state-locking-dynamodb-table>"
  }
}
```

As I was testing the setup with Terraform 0.13, I was investigating this [commit](https://github.com/hashicorp/terraform/pull/25134/commits/2c3b0fa570aeb2ce445ccfba3964b50646c24ae7) and noticed they were using the session_name parameter.
I added the "session_name" parameter in the backend block, and boom, it just works.

**Comment by bryantbiggs** [comment]
ah yes, I didn't spot that (and didn't know it was a hard requirement) difference from my configs. are we ok to close this issue out then? @bdelage

**Comment by dvagapov** [comment]
atlantis plan -p verify1a-vpc -- -destroy -refresh=true
