### ISSUE TITLE
Doc or provide sane defaults to only allow requests coming github/bitbucket/gitlab/etc providers

### ISSUE THREAD

**Issue by nitrocode** [terraform-aws-modules/terraform-aws-atlantis#146]
Since github requires webhook access hit a public ALB, this ALB is open to the world. It would be useful to setup a security group that would only allow a set of ingress IP addresses to reduce blast radius.

This concerned me because I was able to hit the public ALB and discard a lock, unauthenticated.

* [Github IPs](https://api.github.com/meta)
    * I believe we only care about the [hooks](https://developer.github.com/v3/meta/)
    * `192.30.252.0/22`
    * `185.199.108.0/22`
    * `140.82.112.0/20`
* [Bitbucket IPs](https://support.atlassian.com/bitbucket-cloud/docs/what-are-the-bitbucket-cloud-ip-addresses-i-should-use-to-configure-my-corporate-firewall/)
    * `104.192.136.0/21`
    * `185.166.140.0/22`
    * `18.205.93.0/25`
    * `18.234.32.128/25`
    * `13.52.5.0/25`
* [Gitlab IPs](https://docs.gitlab.com/ee/user/gitlab_com/#ip-range) plus the [cloudflare IPs](https://www.cloudflare.com/ips-v4)
    * `34.74.90.64/28`
* And of course, your office IPs

## Proposal

* [ ] set good defaults and allow `var.alb_ingress_cidr_blocks` to append or supplant defaults based on git provider selected
* [ ] document the additional security measure using the above references

## Workaround

```
module "atlantis" {
  ...

  alb_ingress_cidr_blocks = [
    # office/vpn ips
    ...
    # github
    "192.30.252.0/22",
    "185.199.108.0/22",
    "140.82.112.0/20",
    # bitbucket
    "104.192.136.0/21",
    "185.166.140.0/22",
    "18.205.93.0/25",
    "18.234.32.128/25",
    "13.52.5.0/25",
    # gitlab
    "34.74.90.64/28",
    # cloudflare
    ...
  ]

  ...
}
```

**Comment by osterman** [comment]
Ya, I like this idea. Btw, our module supports OIDC too, which is helpful for securing the page for discarding locks.

Should we create a `alb_allowed_cidr_blocks` (or `permitted`) and another for canned policies?

`alb_allowed_cidr_list = [ "github", "bitbucket", "gitlab"]` and the user can specify any number of them.

I'd like a better name than list, but didn't like `canned_cidr_blacks` and couldn't think of another.

**Comment by osterman** [comment]
Fwiw, we chose to limit it using OIDC in the [cloudposse module](https://github.com/cloudposse/terraform-aws-ecs-atlantis). But I still like the idea of limiting webhooks to the various VCS providers.

**Comment by tjtaill** [comment]
Just wanted to add a comment that those bitbucket ips are not complete I took a more complete list from here https://ip-ranges.atlassian.com/

which gives

alb_ingress_cidr_blocks = [

    # bitbucket / atlasian
    "52.41.219.63/32",
    "34.216.18.129/32",
    "13.236.8.128/25",
    "18.246.31.128/25",
    "34.236.25.177/32",
    "185.166.140.0/22",
    "34.199.54.113/32",
    "35.155.178.254/32",
    "52.204.96.37/32",
    "35.160.177.10/32",
    "52.203.14.55/32",
    "18.184.99.128/25",
    "52.215.192.128/25",
    "104.192.136.0/21",
    "18.205.93.0/27",
    "35.171.175.212/32",
    "18.136.214.0/25",
    "52.202.195.162/32",
    "13.52.5.0/25",
    "34.218.168.212/32",
    "18.234.32.128/25",
    "34.218.156.209/32",
    "52.54.90.98/32",
    "34.232.119.183/32",
    "34.232.25.90/32"
  ]
