### ISSUE TITLE
Provide SSH keys for cloning tf modules

### ISSUE THREAD

**Issue by chrissng** [terraform-aws-modules/terraform-aws-atlantis#15]
More info here: https://www.terraform.io/docs/enterprise/workspaces/ssh-keys.html

There are common use cases where Terraform configurations can pull in Terraform modules from private Git repositories. To be able to access a private Git repository, it would typically require an SSH key or HTTPS login credentials.

This module will be of tremendous value if it allows supplying of SSH keys.

**Comment by statwoodland** [comment]
This would be ideal. I'm having to move away from using this module solely because I can't inject an SSH key.

**Comment by antonbabenko** [comment]
I understand. PR is welcome if anyone has time.

**Comment by eupestov** [comment]
@antonbabenko I'm wondering what would be the best way to implement this? 
- Add another input parameter for the private ssh key and save it in a SSM parameter as it is done for tokens currently.
- Generate a key pair within the module, store in SSM and return the public key in output params.
- Use an existing SSM parameter for fetching the private key.
- Something else?
Please, advise.

**Comment by Vlaaaaaaad** [comment]
@eupestov that's along the lines of what we did, but we used a custom wrapper Docker image that at startup gets the key from SSM.

@bmihaescu is working on a blog post detailing all this.

**Comment by antonbabenko** [comment]
I think that this module should not be very smart and generate keys or save them in SSM but instead, it should either:
1. Control the URL or SSM parameter where secret should be fetched when the container starts and set an environment variable to instruct Git to use SSH key. See [comment](https://github.com/runatlantis/atlantis/issues/176#issuecomment-403723892) by [Paul](/psalaberria002) (Hi there :))
1. Alternatively, which is a more popular solution (according to my knowledge), as @Vlaaaaaaad has mentioned - customize Docker image, get secret at startup from S3 or SSM.

I recommend that we add description of this process in README and include code-snippets there.

Also, it is important to avoid handling of the secret using Terraform to keep it outside of terraform.tfstate.

@psalaberria002 Do you have any ideas about this? Or objections?

**Comment by eupestov** [comment]
Thanks! I'll try the method described by @Vlaaaaaaad first as I already use a custom docker image. But I think I will still need to extend the policy granting the fargate task rights to read specific parameters from SSM.

**Comment by trebidav** [comment]
@antonbabenko Why do you think it's important to not keep the SSH key in .tfstate file? Other secrets are also kept there. The bigger problem is that you need a custom docker image with SSH config and mechanism of importing SSH key on startup. This would need to get official support from atlantis server. I don't think that this feature should be part of this module. @Vlaaaaaaad @bmihaescu However a blog post would be nice!

**Comment by antonbabenko** [comment]
It is a private key, not public. This is a bit too much to keep in tfstate.

I think if we can get a process (eg, a script) which creates necessary adjustments it would be handy to have it in this repository at least.

**Comment by jkodroff** [comment]
If it helps, you can reference the work that I did in creating the public Helm chart for Atlantis: https://github.com/helm/charts/tree/master/stable/atlantis

We add trickery to .gitconfig to force HTTPS over SSH and substitute the supplied user token in the URL:
https://github.com/helm/charts/blob/master/stable/atlantis/values.yaml#L41-L52

**Comment by smiller171** [comment]
> Unfortunately, I'm not sure to what extent Fargate allows mounting secrets as files. I suppose it could always be done via the CLI at startup.

It only supports secrets as environment variables and files [link](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data.html), but you could use custom workflows to access that environment variable, or you could use a custom container to get the environment variable and save it to a file.

**Comment by lindehoff** [comment]
One quick fix would be to expose the `command` input variable for the container_definition_github_gitlab definition. Then you could add the following run cmd `["sh", "-c", "git config --system url.https://oauth2:$YOUR_GITLAB_TOKEN@gitlab.com.insteadof ssh://git@gitlab.com && atlantis server"]` to the container and it will configure git to use https with token instead of ssh key. You of course need to add the environment variable YOUR_GITLAB_TOKEN also.

**Comment by brunsgaard** [comment]
https://github.com/terraform-aws-modules/terraform-aws-atlantis/issues/63#issuecomment-591979875
