### ISSUE TITLE
When using github ssm parameter for user token, the IAM policy for atlantis doesn't get created, meaning the webhook secret can't be read.

### ISSUE THREAD

**Issue by JacobWeyer** [terraform-aws-modules/terraform-aws-atlantis#159]
https://github.com/terraform-aws-modules/terraform-aws-atlantis/blob/master/main.tf#L421

This line here prevents the IAM policy from being created when using an ssm parameter for the token.

**Comment by bryantbiggs** [comment]
duplicate #104
