### ISSUE TITLE
Integrate Authy to handle MFA and allow "atlantis apply" for verified users

### ISSUE THREAD

**Issue by antonbabenko** [terraform-aws-modules/terraform-aws-atlantis#16]
Authy has application requests feature which allows sending a request to a user to confirm his intention.

API docs:
https://www.twilio.com/docs/authy/api

**Comment by Vlaaaaaaad** [comment]
I'd love to see support for this. We were thinking of doing this with a script that was to be called before apply, but integration directly into Atlantis would be awesome.

Also, Okta( [API docs](https://developer.okta.com/docs/api/resources/users)) support would be great too.

**Comment by Vlaaaaaaad** [comment]
This can likely be closed in favor of https://github.com/runatlantis/atlantis/issues/309.

**Comment by antonbabenko** [comment]
Agree, closing this one here.
