### ISSUE TITLE
AWS provider 3.22.0 issue

### ISSUE THREAD

**Issue by ivanmartos** [terraform-aws-modules/terraform-aws-atlantis#178]
After upgrading aws provider to `3.22.0` from `3.12.0` . Error occurs also on aws provider `3.27.0`
`terraform apply` gives following error

```
module.atlantis.data.aws_ecs_task_definition.atlantis: Refreshing state...

Error: Provider produced inconsistent final plan

When expanding the plan for module.atlantis.aws_ecs_service.atlantis to
include new values learned so far during apply, provider
"registry.terraform.io/-/aws" produced an invalid new value for
.wait_for_steady_state: was cty.False, but now null.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

Atlantis module version - `2.31.0`

Terraform version - `0.12.29`

**Comment by ivanmartos** [comment]
I guess it's related to https://github.com/hashicorp/terraform-provider-aws/issues/16526

**Comment by antonbabenko** [comment]
Probably, it is related to the issue you are referring to. Closing this issue here.
