### ISSUE TITLE
Github provider configuration in the submodule "github-repository-webhook" too explicit

### ISSUE THREAD

**Issue by scream314** [terraform-aws-modules/terraform-aws-atlantis#179]
With the current state of the submodule `github-repository-webhook` I cannot create webhooks on my self-hosted GitHub Enterprise server.
Even if I'm passing in a named provider like
```
module "atlantis_github-repository-webhook" {
[...]
  providers                   = {
    github = github.this
  }
}
```
I'm getting
```
Error: POST https://api.github.com/repos//example/hooks: 404 Not Found []
```
on creation, so it is not respecting my `provider.github.base_url`.

But if I am using a local copy of the sub-module and remove the whole `provider`, I can create webhooks by invoking the module as
```
module "atlantis_github-repository-webhook" {
  source                      = "/path/to/local/copy/of/modules/atlantis/github-repository-webhook"

  atlantis_allowed_repo_names = ["example"]
  webhook_url                 = "https://atlantis.example.com/events"
  webhook_secret              = "asdasdasdsecret"

# I guess explicitly calling the provider is not necessary, but this is how I tested it and worked
  providers                   = {
    github = github.this
  }
}
```

If anyone has a suggestion how to properly fix this (one way would be to remove the provider block, and pass it from the place this is called), I would be more than happy to open a PR (so I can switch back to the upstream implementation).

**Comment by bryantbiggs** [comment]
@scream314 can you try using a later version of the GitHub provider in your backend config like
```hcl
    github = {
      source  = "integrations/github"
      version = ">= 4.0"
    }
```

**Comment by bryantbiggs** [comment]
closing for now, please feel free to respond if this is still an issue
