### ISSUE TITLE
Http lb listener can not be turned off

### ISSUE THREAD

**Issue by BenLeibig** [terraform-aws-modules/terraform-aws-atlantis#181]
There is no way to disable the http lb listener.  There's a lot of potentially sensitive data being passed between Atlantis and GitHub.  It seems silly to have http turned on, and problematic not to be able to turn it off.

Is there a reason for this?

**Comment by bryantbiggs** [comment]
hi @BenLeibig, its common practice to have http redirected to https and that is what we have done in this module https://github.com/terraform-aws-modules/terraform-aws-atlantis/blob/2bef68a4245518ad6d7516d65b3b2576eeb04ec3/main.tf#L221
