### ISSUE TITLE
v2.33.0 breaks compatibility with Terraform v0.12

### ISSUE THREAD

**Issue by figaw** [terraform-aws-modules/terraform-aws-atlantis#185]
The readme states that 
> Terraform 0.12 or newer. Pin module version to ~> v2.0. 

But <https://github.com/terraform-aws-modules/terraform-aws-atlantis/blob/v2.33.0/versions.tf> introduces,

> `required_version = ">= 0.13"`

This should've been a major bump, right? Our plan suddenly isn't deploying anymore, because we use Terraform `v0.12.29`.

**Comment by antonbabenko** [comment]
@figaw Please use [v2.35.0](https://github.com/terraform-aws-modules/terraform-aws-atlantis/releases/v2.35.0) where the Terraform requirements were restored to support 0.12.
