### ISSUE TITLE
Better integration with a deployment pipeline

### ISSUE THREAD

**Issue by LuigiClemente-Awin** [terraform-aws-modules/terraform-aws-atlantis#187]
Hi all

I was wondering if this module has been designed with the idea of an external build/deployment pipeline in place.
If you have a custom atlantis image integrating several other tools and configurations that changes frequently, the idea of updating the terraform template and apply is not ideal. I am not an expert but it looks like there are several issue with this module in this regard.

Using AWS Codepipeline or Code Deploy is not possible, apparently, because it expects to find two target groups in the load balancer and use a blue-green deployment. The module only creates one target group.

Using external tools to create a new image and update the task definition still leaves the issue that the state file is out-of-date and will revert the deployment when terraform runs again. To avoid this we need the option to add lifecycle configuration inside the module code itself, that is outside our control.

I might have misunderstood or missed something, I would be interested in your feedback on this.

Best,

Luigi

**Comment by bryantbiggs** [comment]
hello @LuigiClemente-Awin - I'm not certain I follow what you are saying. Are you inquiring about how to use custom images with this module?

**Comment by bryantbiggs** [comment]
closing for now - please feel free to re-open if new information has been provided
