### ISSUE TITLE
2.40.0 failure on atlantis_repo_whitelist

### ISSUE THREAD

**Issue by nickmaccarthy** [terraform-aws-modules/terraform-aws-atlantis#200]
## Description

In 2.40.0 I'm getting the below error doing an init on the new module.  According to the docs, `atlantis_repo_whitelist` is still a valid variable.  Going back to 2.39.0 fixed this issue for me.  Is this variable going away in 2.40.0?

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions
2.40.0
 - Terraform:
0.14.10
 - Provider(s):
 - Module:

## Reproduction
Use v2.40.0, and try to init a project that is using the `atlantis_repo_whitelist` variable
No Workspaces
Yes I have cleared the cache
Went from 2.39.0 to 2.40.0 and the issue started

## Expected behavior
A successful init

## Actual behavior
```Error: Unsupported argument

  on main.tf line 137, in module "atlantis":
 137:   atlantis_repo_whitelist     = ["github.com/${var.github_organization}/*"]

An argument named "atlantis_repo_whitelist" is not expected here.
```

## Additional context
In 2.40.0 the docs still reflect that `atlantis_repo_whitelist` is a valid variable.  Going back to 2.39.0 works.

**Comment by marcoceppi** [comment]
This is a documentation issue, change the value to `atlantis_repo_allowlist` to use v2.40.0 and beyond.
