### ISSUE TITLE
The target group does not have an associated load balancer from github-complete example.

### ISSUE THREAD

**Issue by raksit31667** [terraform-aws-modules/terraform-aws-atlantis#211]
## Description

I tried to provision Atlantis on ECS and Fargate, with Route53 pointing to ALB on VPC, and GitHub webhook underneath `examples/github-complete`. Here is my `terraform.tfvars`:

```
region = "ap-southeast-1"
domain = "raksit31667.xyz"
alb_ingress_cidr_blocks = ["10.0.0.0/32"]
github_organization = "raksit31667"
github_user = "atlantisbot"
github_token = ***
allowed_repo_names = ["repo1", "repo2"]
trusted_principals = ["ssm.amazonaws.com"]
```

After I ran `terraform plan` and `terraform apply`, it took 45 minutes to complete with error since ACM issued certificate status was `PENDING_VALIDATION`.

```
Error: error creating atlantiscomplete service: InvalidParameterException: The target group with targetGroupArn arn:aws:elasticloadbalancing:ap-southeast-1:564702493239:targetgroup/atlantiscomplete/742ab858e2eebb95 does not have an associated load balancer.

  on ../../main.tf line 597, in resource "aws_ecs_service" "atlantis":
 597: resource "aws_ecs_service" "atlantis" {



Error: Error describing created certificate: Expected certificate to be issued but was in state PENDING_VALIDATION

  on .terraform/modules/atlantis.acm/main.tf line 44, in resource "aws_acm_certificate_validation" "this":
  44: resource "aws_acm_certificate_validation" "this" {

```

## Versions
```
Terraform v0.14.11
+ provider registry.terraform.io/hashicorp/aws v3.48.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/integrations/github v4.12.1
```

## Reproduction
1. Configure `terraform.tfvars` as similar as above.
2. Run `terraform init`, `terraform plan` and `terraform apply`.

## Expected behavior
The certificate status should be `PASSED`.

## Actual behavior
An error regarding to the target group not have an associated load balancer, and The certificate status was `PENDING_VALIDATION`.

## Additional context
https://github.com/cds-snc/aws-ecs-fargate/issues/1

**Comment by bryantbiggs** [comment]
this looks to have failed due to your ACM cert not reaching a provisioned state. I have re-run this example locally and all works as intended
