### ISSUE TITLE
ALB HTTPS ssl policy cannot be changed

### ISSUE THREAD

**Issue by LuigiClemente-Awin** [terraform-aws-modules/terraform-aws-atlantis#230]
Hi all

Unless I misunderstood something, it seems to me that once the ALB HTTPS listener has been created with the default "ELBSecurityPolicy-2016-08" ssl policy, this cannot be changed.

I see that the ssl_policy setting is not configurable here:

```
  listener_ssl_policy_default = var.alb_listener_ssl_policy_default
  https_listeners = [
    {
      target_group_index   = 0
      port                 = 443
      protocol             = "HTTPS"
      certificate_arn      = var.certificate_arn == "" ? module.acm.acm_certificate_arn : var.certificate_arn
      action_type          = local.alb_authenication_method
      authenticate_oidc    = var.alb_authenticate_oidc
      authenticate_cognito = var.alb_authenticate_cognito
    },
  ]
```
In the ALB module I see that it will only use the default value:
```
ssl_policy      = lookup(var.https_listeners[count.index], "ssl_policy", var.listener_ssl_policy_default)
```
Since the default policy will not disable tls 1.0 and 1.1 (deprecated) this setup won't pass a security check.
Would it be possible to fix this so it can be changed without destroying and recreating resources?

Thanks,

Luigi

**Comment by bryantbiggs** [comment]
you can configure what policy is used, see [here](https://github.com/terraform-aws-modules/terraform-aws-atlantis/blob/e67534be4caf6ef26a8fd07bca2b14cd0ed096a0/examples/github-complete/main.tf#L85) for example

**Comment by LuigiClemente-Awin** [comment]
Hi Bryant

Thanks, my mistake, I was missing a variable in the terragrunt wrapper and so it kept using the default value.
Thanks a lot for your prompt response.

Best,

Luigi
