### ISSUE TITLE
Providing input for variable policies_arn doesn't allow Terraform for generating plan

### ISSUE THREAD

**Issue by michal-adamkiewicz** [terraform-aws-modules/terraform-aws-atlantis#236]
## Description

I would like to attach custom policies into ECS task execution role that is being created inside module. Accordingly to documentation I was trying to use input: **policies_arn**. Unfortunately it returns me an exception from Terraform CLI:

Error: Invalid for_each argument

  on .terraform/modules/atlantis/main.tf line 432, in resource "aws_iam_role_policy_attachment" "ecs_task_execution":
 432:   for_each = toset(local.policies_arn)

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

 - Terraform: 1.0.9

 - Provider(s): 3.65.0

 - Module: 3.5.0

## Reproduction

 No
 Yes
 terraform init / terraform plan

### Code Snippet to Reproduce

 
policies_arn = [aws_iam_policy.atlantis-assume-roles.arn]

**Comment by antonbabenko** [comment]
This is a limitation in Terraform, which requires users to run terraform twice. In your case, it is:
```
terraform apply -target=aws_iam_policy.atlantis-assume-roles
```
before running `terraform apply` to create all resources.

Unfortunately, there is no better solution for this in Terraform.

**Comment by michal-adamkiewicz** [comment]
Thank you very much for explanation!
