### ISSUE TITLE
Redirect HTTP to HTTPS on the ALB

### ISSUE THREAD

**Issue by waeltken** [terraform-aws-modules/terraform-aws-atlantis#24]
Redirect ingress on port 80 HTTP to port 443 HTTPS.

Opening the atlantis page in a browser simply times out but should be redirected to HTTPS.

**Comment by antonbabenko** [comment]
Fixed by @waeltken in [v1.9.0](https://github.com/terraform-aws-modules/terraform-aws-atlantis/releases/v1.9.0).
