### ISSUE TITLE
Error with EFS security group if using existing VPC

### ISSUE THREAD

**Issue by bodgit** [terraform-aws-modules/terraform-aws-atlantis#252]
## Description

If using an existing VPC rather than let this module create it, it now generates this error:
```
│ Error: "" is not a valid CIDR block: invalid CIDR address: 
│ 
│   with module.atlantis.module.efs_sg[0].module.sg.aws_security_group_rule.ingress_rules[0],
│   on .terraform/modules/atlantis.efs_sg/main.tf line 70, in resource "aws_security_group_rule" "ingress_rules":
│   70:   cidr_blocks      = var.ingress_cidr_blocks
│ 
╵
```
This is due to this line:
https://github.com/terraform-aws-modules/terraform-aws-atlantis/blob/2df6bd6d5350d38e42ad9c63103c642f60293a43/main.tf#L382

`var.cidr` doesn't need to be set if you have the VPC already created and are passing it in with `var.vpc_id`.

## Versions

 - Terraform: 1.1.3

 - Provider(s): aws 3.74.2

 - Module: 3.12.0

### Code Snippet to Reproduce
Use this module with the `vpc_id` parameter to use an existing VPC.

## Expected behavior
It shouldn't be erroring, possibly should be using a datasource to get the CIDR block associated with the VPC referenced by `var.vpc_id`.

## Actual behavior
See above.

**Comment by aairey** [comment]
https://github.com/terraform-aws-modules/terraform-aws-atlantis/blob/2df6bd6d5350d38e42ad9c63103c642f60293a43/variables.tf#L62-L66

The description is not correct, when you pass a `vpc_id` you still need to set `var.cidr` as `var.enable_ephemeral_storage` defaults to `false`.

**Comment by dgokcin** [comment]
@aairey so I should give the cidr block of my existing vpc?

**Comment by aairey** [comment]
Yes, but things might've changed now in the latest release. Haven't tried it yet.

**Comment by llamahunter** [comment]
> Yes, but things might've changed now in the latest release. Haven't tried it yet.

It still does not work. There should be no need to specify the VPC CIDR block if you are specifying the vpc_id. The terraform should just look it up if it needs it.

**Comment by asantos-fuze** [comment]
@bodgit I've updated version v3.15.0 with changes you've made on this commit [54bd2d9](https://github.com/bodgit/terraform-aws-atlantis/commit/54bd2d9a043e0e82937aa1ba724e8a08677d3acf) and was able to solve the cidr sg issue. Thanks

**Comment by bryancusatis** [comment]
We are still having this same issue.

**Comment by asantos-fuze** [comment]
@bryancusatis Apply the changes on commit [54bd2d9](https://github.com/bodgit/terraform-aws-atlantis/commit/54bd2d9a043e0e82937aa1ba724e8a08677d3acf) made by @bodgit . This should solve the issue

**Comment by chroju** [comment]
I have the same issue.

Will commit https://github.com/bodgit/terraform-aws-atlantis/commit/54bd2d9a043e0e82937aa1ba724e8a08677d3acf not be merged into this repository ......?　 Shall I create a PR with the same one?
