### ISSUE TITLE
Conditional creation of some resources

### ISSUE THREAD

**Issue by dgokcin** [terraform-aws-modules/terraform-aws-atlantis#270]
## Is your request related to a problem? Please describe.
We are using Cloudflare for DNS management in our organization. When I apply this module, unneeded route 53 resources for my use case are created.

## Describe the solution you'd like.
I would like to have the ability to control the creation of Route 53 related resources.

Is this possible? If not how can I avoid route53 related resource creation and use my own DNS provider?

**Comment by antonbabenko** [comment]
Try disabling it by setting `create_route53_record = false`.

**Comment by dgokcin** [comment]
do I need to have a hosted_zone created?

**Comment by andyshinn** [comment]
I also created my domain external and you need to set 5 params for this to work:

```
  route53_zone_name                = mydomain.com
  create_route53_record            = false
  acm_certificate_domain_name      = mydomain.com
  certificate_arn                  = "<arn_to_my_external_acm>"
  atlantis_fqdn                    = "atlantis.mydomain.com"
```
