### ISSUE TITLE
support setting of runtime_family on ecs_task_definition

### ISSUE THREAD

**Issue by JoshiiSinfield** [terraform-aws-modules/terraform-aws-atlantis#273]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality
released in v3.69 of AWS Provider:
https://github.com/hashicorp/terraform-provider-aws/pull/22016

Support for ARM in Atlantis added in v0.19.0:  https://github.com/runatlantis/atlantis/releases/tag/v0.19.0

## Describe the solution you'd like.

I'd like to run Atlantis on ARM64 to reduce costs and get increased performance on Fargate.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 3.16.0 :tada:
