### ISSUE TITLE
Dinamically create ecs task access secrets policy

### ISSUE THREAD

**Issue by bpastiu** [terraform-aws-modules/terraform-aws-atlantis#274]
## Is your request related to a problem? Please describe.
I was wondering if the ecs_task_acces secrets policy could be dinamically created. I see here: https://github.com/terraform-aws-modules/terraform-aws-atlantis/blob/fab764c06444a0e72deb6c3cf92bdb4fbc31ba4b/main.tf#L535 that it is currently hardcoded to those specific ssm paramters. 

## Describe the solution you'd like.
In my current setup I also need some values for other app/api keys (datadog keys required by the datadog provider). Those are stored as ssm parameters and it would be of much help if I could just read their value and add it as env vars (using the "custom_environment_secrets" for example). It is required in my setup as we have datadog resources along with aws resources 

## Additional context
Thanks for all the hard work.

**Comment by antonbabenko** [comment]
Hi,

This module does not handle this natively because there are a lot of combinations for various use cases. You should make a custom IAM policy and pass it into `policies_arn` argument.

You are welcome.

**Comment by bpastiu** [comment]
Thanks so much for the reply. Just started using this and it's awesome. Will do, thanks for the tip.
