### ISSUE TITLE
Python installation on Atlantis

### ISSUE THREAD

**Issue by abalcobia** [terraform-aws-modules/terraform-aws-atlantis#280]
## Is your request related to a problem? Please describe.
When I try to integrate Atlantis with repos with python files, I get the following error:

![image](https://user-images.githubusercontent.com/98830742/168612940-0d299369-9dc7-4212-a03c-b28b445a6982.png)

I have done some tests by adding the command and entrypoint inputs with python installation commands but without success, since after installing the packages, the container stops and consequently Atlantis too.

## Describe the solution you'd like.
Could you help me to clarify/understand if there is any solution to install python on Atlantis container through the module,  without having to change the docker file (this assumes constant updating of the image whenever there are new updates -> ( + effort management)? 

Any thoughts? Thanks in advance!

**Comment by bryantbiggs** [comment]
You will either need the upstream Atlantis image to ship python or you will have to create your own image that has python installed that you can then use with the module.

**Comment by abalcobia** [comment]
Thanks for the clarification @bryantbiggs!

**Comment by DrFaust92** [comment]
Closing this as its not a module issue.
