### ISSUE TITLE
Show an overview of cost of running Atlantis in Fargate

### ISSUE THREAD

**Issue by Th0masL** [terraform-aws-modules/terraform-aws-atlantis#301]
Hi !

I'm curious to run Atlantis and I would like to have an idea what would approximately be the monthly cost of running it in Fargate using the Terraform Stack provided in this repo.

I assume it would depend on the number of containers that are running, but maybe we can have a global overview already ?

Thanks !

Thomas

**Comment by joerawr** [comment]
Hi,
I have this setup in an account with no other ECS or ECR, so I can give you my costs.

Daily I see $0.30/day for ECS, and less than a penny a day for ECR storage of the image (I tweaked it a little, so I store it in ECR.  You might not need to), so monthly ~$9 for one task/container.  That is not including the EFS.  I am only using 1GB EFS, so at $0.043GB/mo, I should still be right about that $9.  Call it $10/mo to be safe.

This is with the default sizing:
`variable "ecs_task_cpu" {
  description = "The number of cpu units used by the task"
  type        = number
  default     = 256
}

variable "ecs_task_memory" {
  description = "The amount (in MiB) of memory used by the task"
  type        = number
  default     = 512
}`

(I've yet to get multiple containers to work with EFS storage, but that'll be a different issue.)

**Comment by Th0masL** [comment]
Hi,
The cost is indeed really affordable! 
Thank you so much for this very detailed response @joerawr !
