### ISSUE TITLE
How to get atlantis secret without checking tf state file

### ISSUE THREAD

**Issue by chenrui333** [terraform-aws-modules/terraform-aws-atlantis#31]
Hi, 

I am currently using this as `As a Terraform module` approach, but I could not find a good way to do retrieve the token as well as the events url.

The webhook events url is easy to setup though with appending `/events` behind the domain, but how can I get the token that I need for setting up the repo's webohook?

Right now the github_user and github_user_token are passed in as build env variables:
```
  # Atlantis
  atlantis_github_user       = "${var.BOT_USERNAME}"
  atlantis_github_user_token = "${var.BOT_TOKEN}"
  atlantis_repo_whitelist    = ["github.com/org/*"]
```

**Comment by antonbabenko** [comment]
If you are using it as a module you need to make sure that you are returning the output of `${module.atlantis.webhook_secret}` from the module upwards to parent module.

`webhook_secret` and `atlantis_url` are returned by this module:
https://github.com/terraform-aws-modules/terraform-aws-atlantis/blob/8d58540eaa56feb352f8be2121d64bcafa9324bf/outputs.tf#L21-L24

**Comment by chenrui333** [comment]
Yeah, I thought the same thing, I can access `atlantis_url` though, but somehow the `webhook_secret ` is not accessible:
```
output "webhook_secret" {
  description = "Alantis webhook URL"
  value       = "${module.atlantis.webhook_secret}"
}

Error: output 'webhook_secret': "webhook_secret" is not a valid output for module "atlantis"
```

But I can see it in the state list `module.atlantis.random_id.webhook`.

**Comment by chenrui333** [comment]
```
output "atlantis_url" {
  description = "Alantis URL"
  value       = "${module.atlantis.atlantis_url}"
}

[terragrunt] 2019/01/31 12:13:51 Running command: terraform output
atlantis_url = https://atlantis.domain.io
```

**Comment by chenrui333** [comment]
This is basically all the code, I did almost the same as in the README.

```
module "atlantis" {
  source = "terraform-aws-modules/atlantis/aws"

  name = "atlantis"

  # VPC
  cidr            = "10.20.0.0/20"
  azs             = ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
  private_subnets = ["10.20.1.0/24", "10.20.2.0/24", "10.20.3.0/24"]
  public_subnets  = ["10.20.101.0/24", "10.20.102.0/24", "10.20.103.0/24"]

  # DNS (without trailing dot)
  route53_zone_name = "example.com"

  # ACM (SSL certificate) - Specify ARN of an existing certificate or new one will be created and validated using Route53 DNS
  certificate_arn = "arn:aws:acm:eu-west-1:135367859851:certificate/70e008e1-c0e1-4c7e-9670-7bb5bd4f5a84"

  # Atlantis
  atlantis_github_user       = "atlantis-bot"
  atlantis_github_user_token = "examplegithubtoken"
  atlantis_repo_whitelist    = ["github.com/terraform-aws-modules/*"]
}
```

**Comment by chenrui333** [comment]
yeah, it does work!

**Comment by antonbabenko** [comment]
Great! `terraform refresh` is enough. `terraform apply` is good too usually.
