### ISSUE TITLE
Add high availability using redis for locking

### ISSUE THREAD

**Issue by nitrocode** [terraform-aws-modules/terraform-aws-atlantis#322]
## Is your request related to a new offering from AWS?
It is not

## Is your request related to a problem? Please describe.

Id like an HA setup so atlantis can run plans across different projects simultaneously instead of linearly

## Describe the solution you'd like.

Add option to create redis for locking, configure iam policy, add options to atlantis

## Describe alternatives you've considered.

N/A

## Additional context

Related https://github.com/runatlantis/atlantis/issues/1571

https://www.runatlantis.io/docs/server-configuration.html#redis-host

**Comment by dynamike** [comment]
Would it be possible to add some more docs for Atlantis on how to properly use Redis for high availability? That would help adding support for the functionality in this repo.

**Comment by nitrocode** [comment]
unstale

**Comment by nitrocode** [comment]
Unstale

**Comment by nitrocode** [comment]
Unstale

**Comment by bryantbiggs** [comment]
Do we have a design spec for this yet?

**Comment by nitrocode** [comment]
Unsure about a design spec.

Basically

1. Create redis (elasticache)
2. Set appropriate inputs to atlantis to access the redis instance
3. Ensure security group on elasticache allows ingress from atlantis pod/ecs-service
4. Spin up more than one atlantis pod/ecs-service

At least, that's how I understand it.

**Comment by andyshinn** [comment]
What do the Redis hosts do right now if they do not do locking? I'd love to scale Atlantis a bit as it can be slow with many projects and when multiple repos plan / apply at the same time. The docs are unclear if it is for running multiple instances or something else.

**Comment by bryantbiggs** [comment]
The locking seems like the least of the concerns, where do the planned outputs live?

**Comment by nitrocode** [comment]
Hmm that's a good point. I'll reach out to the developers on this to see. Perhaps all of the instances need to share the same volume mount for this to work.

cc @lilincmu @SudoSpartanDan @jamengual 

The PR that implemented this feature https://github.com/runatlantis/atlantis/pull/2491

**Comment by bryantbiggs** [comment]
maybe its just a naming misnomer - but it looks like the `lockingDB` is really storing the locks as well as the plans based on this definition https://github.com/terraform-aws-modules/terraform-aws-atlantis/issues/322#issuecomment-1446259859

**Comment by bryantbiggs** [comment]
Cool - I think it looks straightforward, thanks for sharing that PR @nitrocode 

We'll need a few bits before we can add this but most are already in progress:
1. Update ECS module to include support for service, task definition, and autoscaling. We have most of that already scoped out in this fork https://github.com/clowdhaus/terraform-aws-ecs so we can test and validate on a number of examples https://github.com/aws-ia/ecs-blueprints/pull/109 - once we get this validated I'll open a PR to the main project to get those changes reviewed and merged
2. We'll need an elasticache cluster - I started on a module for this awhile back but never finished. I can revive that and see about getting it added 
3. Once those pieces are in place we can start carving out the changes here

This is great - I know this has been a long sought after feature so I'm excited to see this get added!

**Comment by nitrocode** [comment]
To save time, could we skip step 2 and use https://registry.terraform.io/modules/cloudposse/elasticache-redis/aws/latest module?

**Comment by bryantbiggs** [comment]
Possibly - the philosophy across the modules between the two groups is quite a bit different. Specifically the use of several nested sub-modules and the use of labels and context objects. We'll see

**Comment by nitrocode** [comment]
hmm on second thought, I do not think that redis holds the plans and the feature seems to be a bit wonky. I'm hesitant to push this forward until some of the bugs are fixed with it.

https://github.com/runatlantis/atlantis/issues/1571#issuecomment-1453776159

Thank you for considering.

**Comment by dynamike** [comment]
It would also be helpful to have more documentation in the Atlantis codebase around this feature, so folks know when and why they would enable it vs just running it by default.
