### ISSUE TITLE
`container_memory_reservation` get commented out ?

### ISSUE THREAD

**Issue by chenrui333** [terraform-aws-modules/terraform-aws-atlantis#33]
Just curious why this line got commented out:
https://github.com/terraform-aws-modules/terraform-aws-atlantis/blob/master/main.tf#L321

**Comment by antonbabenko** [comment]
Maybe it is not supported in Fargate? I don't have another idea at the moment without reading docs.

If you think it should be fixed - don't hesitate with PR. :)

**Comment by chenrui333** [comment]
yeah, I feel like the same way, I am happy to do a PR and test on my end. 😄

**Comment by chenrui333** [comment]
Closing the issue now.
