### ISSUE TITLE
Easy to inject environments into `container_definitions`

### ISSUE THREAD

**Issue by chenrui333** [terraform-aws-modules/terraform-aws-atlantis#34]
### Problem 
I need to inject environment variables to the ECS `container_definitions` regarding the API tokens for different terraform providers (like fastly, pagerduty, etc.)

### Ideas
Initially I was thinking to create a new `container_definition` module to override the existing one. 
Per this code, `container_definitions = "${var.custom_container_definitions == "" ? module.container_definition.json : var.custom_container_definitions}"`

But then I realize it is pretty parameterized already inside this module and what I want is just override the environment list. So I guess maybe I just need to override the list?

What would be the better way?

**Comment by stephencoe** [comment]
Also just ran into this problem. Another approach is to allow passing custom environment / secrets through which will be included on the container

```
environment = [
  {
    name  = "ATLANTIS_ALLOW_REPO_CONFIG"
    value = "${var.allow_repo_config}"
  },
  ...
  "${var.custom_environment_variables}",
]

secrets = [
  {
    name      = "${local.secret_name_key}"
    valueFrom = "${local.secret_name_value_from}"
  },
  ...
  "${var.custom_environment_secrets}",
]
```

**Comment by chenrui333** [comment]
@stephencoe Does this work for you, somehow, my atlantis still complain about retrieving the credentials?
