### ISSUE TITLE
No github-org flag to create github app from organization

### ISSUE THREAD

**Issue by samlaf** [terraform-aws-modules/terraform-aws-atlantis#345]
Following the directives for creating a github app (https://registry.terraform.io/modules/terraform-aws-modules/atlantis/aws/latest#using-github-app), which point to the atlantis docs (https://www.runatlantis.io/docs/access-credentials.html#github-app), which require passing this flag to the atlantis server:

> If installing as an Organization, remember to add --gh-org your-github-org to this command.

There doesn't seem to be any such flag in the terraform module, and the default behavior tries to create the app for my user instead of the org.

**Comment by rouge8** [comment]
I think https://github.com/terraform-aws-modules/terraform-aws-atlantis/pull/336 fixes this

**Comment by samlaf** [comment]
Seems like it indeed. Feel free to close. When is that PR going to be merged/released?

**Comment by aalvarezaph** [comment]
@antonbabenko updated that PR branch with main, so looks promising :)
