### ISSUE TITLE
Recommended resource minimums and autoscaling setup?

### ISSUE THREAD

**Issue by samlaf** [terraform-aws-modules/terraform-aws-atlantis#346]
## Is your request related to a problem? Please describe.

We are facing pretty bad latency when using this server and planning 20 different workspaces at the same time. Even for a single workspace it's pretty slow. Noticed that the `ecs_task_cpu` and `ecs_task_memory` are set to 256 (1/4 CPU) and 512 MB  respectively, which is veerry low. Fargate also seems to be very bad at vertical scaling (bursting) according to [this issue](https://github.com/aws/containers-roadmap/issues/163), which would explain why our server doesn't scale fast enough to handle the 20 parallel plans.

The only other reason I see for using Fargate otherwise is if the atlantis server could somehow accomodate horizontal scaling. The `ecs_service_desired_count` parameter is set to 1 as default however, and autoscaling is turned off (don't even see a variable to enable it...). The [complete example](https://github.com/terraform-aws-modules/terraform-aws-atlantis/tree/master/examples/github-complete) uses an ALB however, which seems to indicate horizontal scaling is happening??

## Describe the solution you'd like.

I might be misunderstanding something, but I don't understand why atlantis is being run on ecs/fargate. I would like to see some more extensive (there is currently none, at all) discussion on the setting of the resource parameters and auto-scaling properties. Otherwise, it might make more sense to give the possibility to run this on an ec2 instance?

**Comment by bryantbiggs** [comment]
Atlantis itself does not have great support for horizontal/parallelized scaling and therefore the recommendation would be to:
1. Increase the task size resources (cpu and memory)
2. Look at optimizing how changes are detected and handled within Atlantis to avoid unnecessary plans on no-op changes (given you are using workspaces, I suspect you won't be able to benefit from this though)

In short, there isn't anything that this module can do to alleviate your issues at this time
