### ISSUE TITLE
Expose /metrics endpoint through unauthenticated access

### ISSUE THREAD

**Issue by cblkwell** [terraform-aws-modules/terraform-aws-atlantis#364]
## Is your request related to a problem? Please describe.
For many cases, such as exposing to an external provider, it would be nice to be able to expose the `/metrics` endpoint via an unauthenticated connection like we do `/events` to certain IP ranges (our Prometheus server, or DataDog collectors, or whatever).

## Describe the solution you'd like.
The best method here is probably to just define another variable like `allow_unauthenticated_metrics_cidr_blocks` and `allow_unauthenticated_metrics_priority` as there is for github webhooks, and then add a new `aws_alb_listener_rule` resource similar to the one for `/events`.

## Describe alternatives you've considered.
We can add this listener rule resource ourself outside of the module (which is what we're doing now) but it would be nicer if it was just integrated into the module.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 4.0.0 :tada:
