### ISSUE TITLE
Can we make the ALB Subnet Type agnostic?

### ISSUE THREAD

**Issue by ChrisJBurns** [terraform-aws-modules/terraform-aws-atlantis#365]
## Is your request related to a problem? Please describe.
We currently deploy our ALB in private subnets within AWS. But the [var that is used in the `alb` module](https://github.com/terraform-aws-modules/terraform-aws-atlantis/blob/2200b5690927dc53459190670ea90de299292251/main.tf#L247) makes reference to `local.public_subnet_ids`. 

For now, we have passed in our private subnet id under the `var.public_subnet_ids` with a big comment detailing why - but as you can imagine, it's not ideal.

## Describe the solution you'd like.
I'd like the subnet variable names to be agnostic as it makes assumptions on the type of subnets people use for their ALB's, as many deploy ALB's into private subnets, it's not just public ones.

**Comment by bryantbiggs** [comment]
resolved in #366
