### ISSUE TITLE
Invalid index  in module "ecs_service" in v 4.0.1

### ISSUE THREAD

**Issue by alexandreags** [terraform-aws-modules/terraform-aws-atlantis#369]
## Description

│ Error: Invalid index
│ 
│   on main.tf line 378, in module "ecs_service":
│  378:             access_point_id = module.efs.access_points["atlantis"].id
│     ├────────────────
│     │ module.efs.access_points is object with no attributes
│ 
│ The given key does not identify an element in this collection value.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version 4.0.1:

- Terraform version:
1.5.7
- Provider version(s):
5.24.0

## Actual behavior

Module install successfully

### Terminal Output Screenshot(s)

│ Error: Invalid index
│ 
│   on main.tf line 378, in module "ecs_service":
│  378:             access_point_id = module.efs.access_points["atlantis"].id
│     ├────────────────
│     │ module.efs.access_points is object with no attributes
│ 
│ The given key does not identify an element in this collection value.

## Additional context

I have fixed this (temporarily) changing the logic to:

378: access_point_id = try(module.efs.access_points["atlantis"].id, "")

I dont know if this is ideal, but is a workaround

**Comment by bryantbiggs** [comment]
thank you - this should be fixed in #370

**Comment by antonbabenko** [comment]
This issue has been resolved in version 4.0.2 :tada:
