### ISSUE TITLE
Document that setting ATLANTIS_GH_USER breaks the github app (ATLANTIS_GH_APP_ID / ATLANTIS_GH_APP_KEY) scenario

### ISSUE THREAD

**Issue by d33psky** [terraform-aws-modules/terraform-aws-atlantis#381]
## Is your request related to a problem? Please describe.

The combination of

1. ATLANTIS_GH_USER
2. ATLANTIS_GH_APP_ID / ATLANTIS_GH_APP_KEY

breaks starting the service with : 

`Error: --gh-user/--gh-token or --gh-app-id/--gh-app-key-file or --gh-app-id/--gh-app-key or --gitlab-user/--gitlab-token or --bitbucket-user/--bitbucket-token or --azuredevops-user/--azuredevops-token must be set
`
## Describe the solution you'd like.

Add text to https://github.com/terraform-aws-modules/terraform-aws-atlantis/blob/master/docs/README.md that describes that no ATLANTIS_GH_USER must be specified for the GitHub app scenario

**Comment by bryantbiggs** [comment]
we don't need to document that here - we follow the Atlantis docs https://www.runatlantis.io/docs/server-configuration.html#gh-user
