### ISSUE TITLE
Atlantis default UID of 100 vs 1000

### ISSUE THREAD

**Issue by d33psky** [terraform-aws-modules/terraform-aws-atlantis#382]
## Description

Using the default Atlantis Docker module https://github.com/runatlantis/atlantis/blob/main/Dockerfile breaks because of a UID setting with this modules default at https://github.com/terraform-aws-modules/terraform-aws-atlantis/blob/master/variables.tf#L31 of 100 as the Docker file makes an atlantis user with UID 1000.

The docker file also makes a user with UID 100, namely sshd . This results in unwanted combinations like : 

`Error: initializing server: unable to create dir "/run/sshd/.atlantis/bin": mkdir /run/sshd: permission denied
`

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Reproduction Code [Required]

Use this module with standard atlantis dockerfile.

## Expected behavior

Starting atlantis process with UID 1000

## Actual behavior

Starting atlantis process with UID 100 , and then failing because atlantis user has no write rights to /run/sshd/ (being sshd home directory)

## Additional context

The dockerfile has ao. these 2 users in /etc/passwd : 
```
sshd:x:100:65534::/run/sshd:/usr/sbin/nologin
atlantis:x:1000:1000::/home/atlantis:/bin/bash
```

When running 'id' in a '/docker-entrypoint.d/' script the output is : 
`id: [uid=100(sshd) gid=1000(atlantis) groups=1000(atlantis)]
`

## Workaround

A workaround for this issue is to specify 
`atlantis_uid = 1000
`
inside the 'module "atlantis" {' block in main.tf .

## Proposed solution

Propose to change https://github.com/runatlantis/atlantis/blob/main/Dockerfile#L144 to 1000 so that it matches with Atlantis' standard Dockerfile

**Comment by bryantbiggs** [comment]
please provide a reproduction - with the examples we have, I am not seeing this error
