### ISSUE TITLE
When EFS is Enabled, the Created EFS File System has an empty 'Name' Tag

### ISSUE THREAD

**Issue by X-Guardian** [terraform-aws-modules/terraform-aws-atlantis#386]
## Description

Specifying `enable_efs = true` causes the module to create an EFS file system, but it has an empty `Name` tag set. This is used by the AWS EFS management console uses for identifying the file system, so would be useful if it was set.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version: `4.0.6`
- Terraform version: `v1.5.5`

## Expected behavior

Set the EFS file system `Name` tag to the value of `var.name`.

## Actual behavior

Empty `Name` tag

### Terminal Output Screenshot(s)

![image](https://github.com/terraform-aws-modules/terraform-aws-atlantis/assets/32168619/8fcab625-f600-4e6b-abec-3e6f92701196)

**Comment by antonbabenko** [comment]
This issue has been resolved in version 4.0.7 :tada:
