### ISSUE TITLE
The ALB Target Group Name is not set to the 'name' Variable

### ISSUE THREAD

**Issue by X-Guardian** [terraform-aws-modules/terraform-aws-atlantis#388]
## Description

The ALB target group that is created by the module has no `name` property specified, so it is being created with a Terraform default name.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version : `4.0.7`

- Terraform version: `1.5.5`

## Expected behavior

Name the ALB target group according to the module `name` variable.

## Actual behavior

The name of the ALB target group is set to a default Terraform name.

### Terminal Output Screenshot(s)

![image](https://github.com/terraform-aws-modules/terraform-aws-atlantis/assets/32168619/0c1ad414-9dce-420f-9afe-c141ea94db16)

**Comment by antonbabenko** [comment]
This issue has been resolved in version 4.0.8 :tada:
