### ISSUE TITLE
Political ware breaks Atlantis module

### ISSUE THREAD

**Issue by lsq-ablair** [terraform-aws-modules/terraform-aws-atlantis#403]
Trying to use a module-generated SSL Certificate via the Atlantis module does not work.

The module referenced has been updated to political-ware, and this breaks the Atlantis module. Suggest limiting the `"acm"` module version to `v3.3.0`.

With any later version, we get the error: `Error: importing ACM Certificate: operation error ACM: ImportCertificate, https response error StatusCode: 400, RequestID: a7780e22-3f96-426f-8d21-3a7957c12b59, api error ValidationException: 2 validation errors detected: Value at 'privateKey' failed to satisfy constraint: Member must have length greater than or equal to 1; Value at 'certificate' failed to satisfy constraint: Member must have length greater than or equal to 1`. This results because you can't define the political variables required to set `create_` to true.

**Comment by bryantbiggs** [comment]
please use the issue template provided and supply the requested details

**Comment by antonbabenko** [comment]
Alternatively, you can just not use these modules if you don't like "politics" in these modules... it is simple...
