### ISSUE TITLE
aws_iam_role_policy_attachment.ecs_task_execution: value of 'count' cannot be computed

### ISSUE THREAD

**Issue by grggls** [terraform-aws-modules/terraform-aws-atlantis#47]
Adding an additional iam policy via the `policies_arn` variable throws the error in the issue description when that additional policy arn is computed:
```
module "atlantis" {
  source  = "terraform-aws-modules/atlantis/aws"
  version = "1.13.0"
  name               = "atlantis"
...
...
  policies_arn               = ["arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy", "${aws_iam_policy.atlantis_run_terraform_policy.arn}"]
}
```

Per https://github.com/hashicorp/terraform/issues/10857, this is Terraform's desired behavior, because we are "performing a function call length on a computed value" and we're trying to call `length` before that value is computed (or the resource created).

`length` is called here -- https://github.com/terraform-aws-modules/terraform-aws-atlantis/blob/master/main.tf#L331

Workaround is to create `aws_iam_policy.atlantis_run_terraform_policy` first, then add it to the module's `policies_arn` var on a subsequent `terraform apply` run. It can't be created and applied in a single run.

**Comment by antonbabenko** [comment]
You are right and there are no better solutions. Another workaround would be to add a variable like `number_of_policies_arn = 2`, which is also ugly.

Closing for now. This won't be an issue in Terraform 0.12.
