### ISSUE TITLE
Atlantis is not aware of the task definition's environments properties

### ISSUE THREAD

**Issue by chenrui333** [terraform-aws-modules/terraform-aws-atlantis#48]

**Comment by antonbabenko** [comment]
Could you be more specific and tell what you provide and what do you expect?

**Comment by chenrui333** [comment]
Sure, sorry to get back late. I have cross-reported in here as well:
https://github.com/runatlantis/atlantis/issues/573

**Comment by chenrui333** [comment]
environment variable typo. 😒
