### ISSUE TITLE
Missing parameters when using own vpc

### ISSUE THREAD

**Issue by Jaff** [terraform-aws-modules/terraform-aws-atlantis#50]
I'm invoking the module `atlantis` using following variable settings:
```
  atlantis_repo_whitelist     = [our primary repository]
  allow_repo_config           = true
  atlantis_allowed_repo_names = []
  atlantis_github_user        = "userbot"
  atlantis_github_user_token  = "EXAMPLE"
  azs                         = "${data.terraform_remote_state.vpc.avail_zones}"
  ecs_service_assign_public_ip = true
  private_subnet_ids            = "${data.terraform_remote_state.vpc.private_subnets}"
  public_subnet_ids             = "${data.terraform_remote_state.vpc.public_subnets}"
  route53_zone_name             = "${data.terraform_remote_state.r53.fqdn}"
  vpc_id                        = "${data.terraform_remote_state.vpc.vpc_id}"
```
But then I get an error message:
`Error: module.atlantis.module.vpc.aws_vpc.this: expected cidr_block to contain a valid CIDR, got:  with err: invalid CIDR address:`

**Comment by Jaff** [comment]
And one more thing, you're asking for lists of public_subnets, public_subnet_ids, private_subnets & private_subnet_ids. Our vpc module outputs the subnet_ids, but are you also asking for subnet names?

**Comment by Jaff** [comment]
I thought it might be due to unequal-length public & private subnets, but I explicitly set both to two and still get the same result. I am providing parameters for all variables, private_subnet_ids, private_subnets, public_subnet_ids, & public_subnets.

**Comment by tebriel** [comment]
I got this same issue, I submoduled this repo and changed [`create_vpc`](https://github.com/terraform-aws-modules/terraform-aws-atlantis/blob/master/main.tf#L139) to be explicitly false, and that fixed my issue. I believe it's because [the ternary](https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/main.tf#L17) in the aws-vpc module doesn't evaluate properly on the boolean value outputted from the check if the vpc id equals `""` or not, but I'm not 100% sure.

**Comment by Jaff** [comment]
Would you please explain how you "submoduled this repo" ?

**Comment by tebriel** [comment]
I forked it, did:
```sh
mkdir -p modules
git submodule add ${git_clone_url} modules/terraform-aws-atlantis
cd modules/terraform-aws-atlantis
git checkout my-fix-branch
cd ../../
git add modules/terraform-aws-atlantis
```

then updated my module as follows
```hcl
module "atlantis" {
  # source  = "terraform-aws-modules/atlantis/aws"
  source  = "./modules/terraform-aws-atlantis"
  # Snip, the rest of the module
```

**Comment by Jaff** [comment]
@tebriel Have you made a PR for your fix?

**Comment by tebriel** [comment]
@Jaff no, I can't find a way to make it work the same way a hardcoded `false` does.

**Comment by Jaff** [comment]
I've gotten a bit farther with this, doing essentially the same as @tebriel but now I'm not able to launch the container. My logs display the command I've provided followed by 'not found' like:
```
/usr/local/bin/docker-entrypoint.sh: exec: line 46: atlantis server --log-level=debug \
--gh-user=XXXX --gh-token="YYYYY" --gh-webhook-secret="something" --repo-config-json='
{
    "repos": [
        {
            "id": "/.*/",
            "allowed_overrides": [
                "workflow"
            ],
            "allow_custom_workflows": true,
            "apply_requirements": [
                "approved",
                "mergeable"
            ]
        }
    ]
}
' --repo-whitelist=github.com/our/repository: not found
```

Where did I go wrong?

**Comment by tebriel** [comment]
why is your json multiline like that? that seems possibly bad, maybe minify it to a single line and see if those newlines are your problem

**Comment by Jaff** [comment]
Gotten past this with different implementation
