### ISSUE TITLE
Only create VPC if no VPC ID is passed

### ISSUE THREAD

**Issue by bsuv** [terraform-aws-modules/terraform-aws-atlantis#6]
https://github.com/terraform-aws-modules/terraform-aws-atlantis/blob/508eb0c3bb99a84dfe9fdbe57f1989be711f4197/main.tf#L18

Great work Anton!

Recently I also developed an Atlantis module to which I pass a `vpc_id` as a variable instead of a `cidr_block` to create a new one - under the assumption that it's more common for someone to deploy Atlantis in an existing VPC.

My proposal:
*  have 2 input variables (`cidr_block` and `vpc_id`), both with dummy defaults.
*  use `count` to determine whether a new VPC is needed, in which case the `cidr_block` would be used.

**Comment by antonbabenko** [comment]
@bsuv Thanks for opening this issue!

You are literally reading my mind. :) I am working on it right now. Expect a PR in a couple of hours with some more enhancements like this.

**Comment by antonbabenko** [comment]
The weather was so good today, so it took me a little bit longer to complete this.

[v1.1.0](https://github.com/terraform-aws-modules/terraform-aws-atlantis/releases/v1.1.0) has been released and there is a possibility to reuse existing VPC and subnets.
