### ISSUE TITLE
aws codecommit support as a git host

### ISSUE THREAD

**Issue by atali** [terraform-aws-modules/terraform-aws-atlantis#64]
We use codecommit to save our state file + tfvars. I am wondering if we can use atlantis to manage our gitops workflow.
Is codecommit could be used a an git host like github or bitbucket ?

**Comment by lkysow** [comment]
Hi Atali, this kind of issue is best opened up in the main Atlantis repo (https://github.com/runatlantis/atlantis) because it's not related to deploying Atlantis in Fargate. I see you've already commented on the existing issue so this one can probably be closed.
