### ISSUE TITLE
Error when using an existing VPC.

### ISSUE THREAD

**Issue by mlcooper** [terraform-aws-modules/terraform-aws-atlantis#70]
I believe https://github.com/terraform-aws-modules/terraform-aws-atlantis/issues/50 should be re-opened.  I am running into this issue using my own VPC.

```
Error: module.atlantis11.module.vpc.aws_vpc.this: expected cidr_block to contain a valid CIDR, got:  with err: invalid CIDR address:
```
I'm not sure I really understand what this line does, https://github.com/terraform-aws-modules/terraform-aws-atlantis/blob/master/main.tf#L148, but I'm not confident that it's NOT trying to create a new VPC.  I am specifying a single `vpc_id` (as a `string`, not a `list`) in my module, calling `terraform-aws-modules/atlantis/aws`

I think a fix would have to be implemented in both the 1.x and 2.x 'branches of this code.  We still have Terraform 11 code in production.

**Comment by bryantbiggs** [comment]
@mlcooper is this still an issue - I am using this module in several places with existing VPCs without issue. if it is still an issue please let me know, otherwise we'll close for now
