### ISSUE TITLE
Provide output of task_role_name

### ISSUE THREAD

**Issue by mlcooper** [terraform-aws-modules/terraform-aws-atlantis#71]
I had to add an IAM policy to the task execution role for the ECS task definition in order to give it permission to GetParameters from the SSM parameter store.  In order to do this via Terraform I needed to reference the role that your terraform-aws-atlantis module creates.  I wasn't sure how to do it other than to fork the code and create an `output` that did this, and then reference it in my module that wraps terraform-aws-atlantis:

```
output "task_role_name" {
  description = "The Atlantis ECS task role name"
  value       = "${aws_iam_role.ecs_task_execution.name}"
}
```
Would it be possible to create this output for the 1.x and 2.x branches of this repo?

**Comment by bryantbiggs** [comment]
@mlcooper this functionality is available now with v2.21.0 per #144
