### ISSUE TITLE
Terragrunt?

### ISSUE THREAD

**Issue by spaszek** [terraform-aws-modules/terraform-aws-atlantis#73]
Hi,

how can we add Terragrunt to the mix?

In this article https://medium.com/@anton.babenko/atlantis-terragrunt-689b1aa2bf89 you mentioned an idea of aliasing `terraform` to `terragrunt`. Would custom docker container with Atlantis(where `terragrunt` is installed and alias applied) be sufficient and "plug-and-play" in this AWS Terraform stack?

**Comment by antonbabenko** [comment]
Hi Tomasz!

The article you are referring to was written more than 1,5 years ago, so it may not reflect the latest state of things.

Nevertheless, answering your question I would recommend to add `terragrunt` binary to your custom docker container and instruct Atlantis to use terragrunt-specific workflow as described in the official documentation [here](https://www.runatlantis.io/docs/custom-workflows.html#use-cases).

This module has nothing to do with your question, so I am going to close it.
