### ISSUE TITLE
Limit ALB SG ingress to GH only (via input variable)

### ISSUE THREAD

**Issue by bsuv** [terraform-aws-modules/terraform-aws-atlantis#8]
https://github.com/terraform-aws-modules/terraform-aws-atlantis/blob/508eb0c3bb99a84dfe9fdbe57f1989be711f4197/main.tf#L47

I found that opening Atlantis to the world is risky and inline with the _principle of least privilege_.
So I restricted it to the CIDR blocks that Github advertises as their own on https://api.github.com/meta
in addition to perhaps the office network, bastion for instance.

PS: I know Atlantis uses the `--repo-whitelist` but adding another layer of (network) security doesn't harm IMO...

**Comment by antonbabenko** [comment]
Agree, https://www.terraform.io/docs/providers/github/d/ip_ranges.html

**Comment by bsuv** [comment]
Didn't know about that data source. Awesome ❤️ 🎉

**Comment by ldormoy** [comment]
How do you access the locks/plan UI if your own IP address isn't allowed?

**Comment by antonbabenko** [comment]
@bsuv Should we close this issue?

**Comment by bsuv** [comment]
Thanks for adding the var @ldormoy! 
@antonbabenko we could still do something like 
```hcl-terraform
"${concat(data.github_ip_ranges.this.hooks, var.alb_ingress_cidr_blocks)}"
```
in order to default `var.alb_ingress_cidr_blocks` to an empty list instead of `["0.0.0.0/0"]` which may not be as secure...
PS: I'll consider addressing this issue a NYE resolution for 2019 :)

**Comment by antonbabenko** [comment]
Happy New Year @bsuv  🎉 ☃️

**Comment by bsuv** [comment]
Happy New Year @antonbabenko :tada: :champagne:

**Comment by bryantbiggs** [comment]
closing this issue for now - GitHub webhook subnets are whitelisted in the current release with the ability to limit IPs accessing the UI
