### ISSUE TITLE
Move container definition into a template_file data source

### ISSUE THREAD

**Issue by bsuv** [terraform-aws-modules/terraform-aws-atlantis#9]
https://github.com/terraform-aws-modules/terraform-aws-atlantis/blob/508eb0c3bb99a84dfe9fdbe57f1989be711f4197/main.tf#L197

Instead of having it inline, it may be more flexible and allow further interpolations :
```
data "template_file" "container" {
  template = "${file("${path.module}/atlantis-container-definition.json")}"
  vars {
    port              = "${var.atlantis_port}"
    log_level         = "${var.log_level}"
    cw_logs_prefix    = "${var.cw_logs_prefix}"
  }
}
```

The above is a minimalistic example. The input variable can have defaults, but module users should have the liberty to easily change them at instantiation time if they want to.

PS: I found that changing Atlantis port from 4141 to 80 helped when accessing it from the office network or via VPN - hence my thought that since they allow it to be changed, why not also have it as an input..

**Comment by antonbabenko** [comment]
Related to #13

**Comment by antonbabenko** [comment]
Done.
