### ISSUE TITLE
Webhook docs out of date?

### ISSUE THREAD

**Issue by mwarkentin** [terraform-aws-modules/terraform-aws-atlantis#90]
I'm in the middle of trying to upgrade from a much older version of atlantis which managed the Github webhooks for you.

The docs still indicate that the module can create the github webhooks for you:

> Github webhook is automatically created if `github_token`, `github_organization` and `github_repo_names` were specified.

However looking at the code I am not seeing how this actually works - I can't find any reference to the `github_repo_names` in the code for example.

I think this functionality might've been removed during the refactor to support gitlab? In any case just wanted to confirm, and wondering what the recommended way to set up the webhooks is now.

**Comment by lkysow** [comment]
Hi Michael, I know you probably want to set these up through terraform but here's the docs on how to do it manually in case you're blocked: https://www.runatlantis.io/docs/configuring-webhooks.html

**Comment by mwarkentin** [comment]
Yep, we got it working (I’ll try to post our updates here or open a doc update PR)

**Comment by demon** [comment]
It would seem one is required to call the respective webhook module themselves. Which is counter-intuitive, seeing as the root module has `atlantis_allowed_repo_names` as a parameter still.

**Comment by smiller171** [comment]
Yeah, At a bare minimum the docs need to be updated

**Comment by lkysow** [comment]
> Yeah, At a bare minimum the docs need to be updated

PRs welcome please!

**Comment by bryantbiggs** [comment]
hi all, I think this is covered under https://github.com/terraform-aws-modules/terraform-aws-atlantis/tree/master/examples/github-complete - if not, please let me know and we can re-open
