### ISSUE TITLE
AWS credentials file not taken into consideration

### ISSUE THREAD

**Issue by negreaandrei** [terraform-aws-modules/terraform-aws-atlantis#97]
Hello. I've tried using your module and I've added my own Atlantis image from v0.11.0 and copied the AWS credentials and config files to the image. From further investigations I realised that the AWS credentials are not retrieved at all from those files, but from the task's role.

2020/02/06 09:14:16 [INFO] Setting AWS metadata API timeout to 100ms
2020/02/06 09:14:16 [INFO] ECS container credentials detected, RemoteCredProvider added to auth chain
2020/02/06 09:14:16 [INFO] Ignoring AWS metadata API endpoint at default location as it doesn't return any instance-id
2020/02/06 09:14:16 [INFO] AWS Auth provider used: "CredentialsEndpointProvider"

Could you help and provide a way so that when terraform runs, to look for the AWS credentials, not the container task role and also to respect the AWS chain of finding credentials.

**Comment by negreaandrei** [comment]
The Dockerfile used to build the image is:
`FROM runatlantis/atlantis:v0.11.0
LABEL authors="foodgraph"

# install pip
RUN apk -v --update add \
        python \
        py-pip \
        groff \
        less \
        mailcap

# install aws cli as atlantis
USER atlantis
RUN pip install --upgrade awscli --user
# copy AWS credentials
COPY aws_credentials /home/atlantis/.aws/credentials
COPY aws_config /home/atlantis/.aws/config

# clean up
USER root
RUN apk -v --purge del py-pip && \
    rm /var/cache/apk/*

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["server"]`

I've added some custom commands on the server side atlantis config file and it turns out that the .aws folder does not exist and is somehow removed from the image. Any idea why?

**Comment by negreaandrei** [comment]
FROM runatlantis/atlantis:v0.11.0
LABEL authors="foodgraph"

# install pip
RUN apk -v --update add \
        python \
        py-pip \
        groff \
        less \
        mailcap

# install aws cli as atlantis
USER atlantis
RUN pip install --upgrade awscli --user
# copy AWS credentials
COPY aws_credentials /home/atlantis/.aws/credentials
COPY aws_config /home/atlantis/.aws/config

# clean up
USER root
RUN apk -v --purge del py-pip && \
    rm /var/cache/apk/*

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["server"]

**Comment by matthewcummings** [comment]
Another way to do this is to grant IAM access to your Atlantis task.

**Comment by bryantbiggs** [comment]
hello @negreaandrei, I think this is counter-intuitive to best practices where static creds should not be put into artifacts like containers. I don't think this would be something worthwhile implementing unfortunately
